
Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/xenial64"
	config.vm.box_check_update = false

	config.vm.provider :virtualbox do |v|
		v.check_guest_additions = false
		v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
		v.memory = 2048
		v.cpus = 1
	end

	config.vm.define "master" do |c|
		c.vm.hostname = "k8s-master"
		c.vm.network "private_network", ip: "10.100.0.10"
		c.vm.provision "shell", path: "setup-master.sh"
	end

	config.vm.define "node" do |c|
		c.vm.hostname = "k8s-node"
		c.vm.network "private_network", ip: "10.100.0.100"
		c.vm.provision "shell", path: "setup-node.sh"
	end

end
