ServerAddress = "spire"
ServerPort = "8081"
TrustDomain = "localhost"
TrustBundlePath = ".conf/carootcert.pem"

BindAddress = "127.0.0.1"
BindPort = "8088"
DataDir = "."
PluginDir = "../../plugin/agent/.conf"
LogFile = "spire-agent.log"
LogLevel = "INFO"
